version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
  producer:
    build: .
    command: ["python", "./src/producer.py"]
    volumes:
      - .:/usr/src/app
    depends_on:
      - rabbitmq
  consumer:
    build: .
    command: ["python", "./src/consumer.py"]
    volumes:
      - .:/usr/src/app
    depends_on:
      - rabbitmq